### ISSUE TITLE
Regards scoped npm packages as invalid

### ISSUE THREAD

**Issue by shawninder** [josa42/atom-linter-package-json-validator#2]
repro: Just make a package.json with a dependency using a scope and watch it complain about an "Invalid dependency package name"

ex:

```
"dependencies": {
  "@scope/package": "^0.0.1"
}
```

**Comment by josa42** [comment]
This is just a wrapper for [gorillamania/package.json-validator](https://github.com/gorillamania/package.json-validator). You need to report the issue there.

**Comment by shawninder** [comment]
Such an issue already exists (https://github.com/gorillamania/package.json-validator/issues/49), but it's closed (the issue has been resolved). Perhaps you need to update that dependency and make a new release?
