### ISSUE TITLE
False negative for "URL not valid for repository"

### ISSUE THREAD

**Issue by dlindahl** [josa42/atom-linter-package-json-validator#7]
Given a dependency with the GitHub URL `git+ssh://git@github.com:USER/REPO.git#v3.0.0`, the validation fails with the message: `Url not valid for repository: USER/REPO at line X col Y`

See also: 

* https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by dlindahl** [comment]
Turns out the validator was complaining about the "repository", not dependencies... Should have paid more attention! :blush:

**Comment by josa42** [comment]
This should be reported to the [gorillamania/package.json-validator](http://github.com/gorillamania/package.json-validator) repo since this package uses it for the actual linting.
